app:
  image:
    repository: my-app-image
    tag: latest
  port: 3003
  env:
    DB_HOST: {{ .Release.Name }}-db
    DB_NAME: tutorial
    DB_USER: vinhle
    DB_PASS: password

db:
  image:
    repository: postgres
    tag: 13-alpine
  port: 5432
  env:
    POSTGRES_DB: tutorial
    POSTGRES_USER: vinhle
    POSTGRES_PASSWORD: password
  storage:
    size: 1Gi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: "standard" # Use default storage class if empty