apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"  # Ensure this matches the PVC's storageClass
  hostPath:
    path: "/mnt/data"  # Adjust this for your environment (if on local, use hostPath)