apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
  - name: http
    protocol: TCP
    port: 3003
    targetPort: {{ .Values.app.port }}
    nodePort: 30033   # External port for NodePort service (range: 30000-32767)
  - name: postgres  # Added name for the second port (for the database)
    protocol: TCP
    port: {{ .Values.db.port }}       # Internal port for the database service
    targetPort: {{ .Values.db.port }}  # Port your database is running on
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
  - protocol: TCP
    port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}