name: Deploy

on:
  push:
    tags: # Trigger pipeline on Git tags
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Kubernetes environment
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CA" > ~/.kube/ca.crt
          echo "$KUBE_TOKEN" > ~/.kube/token
          kubectl config set-cluster my-cluster --server=$KUBE_SERVER --certificate-authority=~/.kube/ca.crt
          kubectl config set-credentials github-action --token=$KUBE_TOKEN
          kubectl config set-context github-action-context --cluster=my-cluster --user=github-action
          kubectl config use-context github-action-context

      - name: Check Kubernetes nodes
        run: kubectl get nodes
        env:
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
          KUBE_CA: ${{ secrets.KUBE_CA }}