name: Build and Push Docker Image

on:
  push:
    tags: # Trigger the pipeline on new Git tags
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Configure Docker daemon for insecure registry
        run: |
          echo '{"insecure-registries": ["158.160.44.209:5000"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Extract Git tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Convert repository name to lowercase
        id: get_lowercase_repo
        run: echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t 158.160.44.209:5000/${{ env.REPO }}:${{ env.TAG }} .

      - name: Push Docker image
        run: |
          docker push 158.160.44.209:5000/${{ env.REPO }}:${{ env.TAG }}

      - name: Verify Docker Registry
        run: |
          curl -s http://158.160.44.209:5000/v2/ || echo "Docker Registry is not reachable"