name: Build, Push, and Deploy

on:
  push:
    tags: # Trigger pipeline on Git tags
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up kubeconfig for Kubernetes
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      # Step 3: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 4: Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      # Step 5: Debug API server connection
      - name: Debug API server connection
        run: curl -k https://${{ secrets.MASTER_IP }}:6443/version
      
      # Step 6: Verify Kubernetes connection
      - name: Verify Kubernetes connection
        run: |
          kubectl get nodes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      # Step 7: Extract Git tag for image versioning
      - name: Extract Git tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
        
      # Step 8: Convert repository name to lowercase
      - name: Convert repository name to lowercase
        id: get_lowercase_repo
        run: echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 9: Configure Docker daemon for insecure registry
      - name: Configure Docker daemon for insecure registry
        run: |
          echo '{"insecure-registries": ["${{ secrets.SRV_IP }}:5000"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      # Step 10: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.SRV_IP }}:5000/${{ env.REPO }}:${{ env.TAG }} .

      # Step 11: Push the Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.SRV_IP }}:5000/${{ env.REPO }}:${{ env.TAG }}

      # Step 12: Deploy application with Helm
      - name: Deploy application with Helm
        env:
          KUBECONFIG: $PWD/kubeconfig
        run: |
          helm upgrade --install app-pw ./helm-chart \
            --set app.image.repository=${{ secrets.SRV_IP }}:5000/${{ env.REPO }} \
            --set app.image.tag=${{ env.TAG }} \
            --set app.service.type=LoadBalancer \
            --set app.service.port=4554 \
            --set app.service.externalIP=${{ secrets.MASTER_IP }}
